QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

DEFINES += LV_CONF_INCLUDE_SIMPLE

INCLUDEPATH += \
  ./lvgl \
  ./app \
  ./hal \

SOURCES += \
    app/app_ui.c \
    app/mainwindow.cpp \
    hal/clabel.cpp \
    hal/lvgl_hal.cpp \
    lvgl/demos/benchmark/assets/img_benchmark_avatar.c \
    lvgl/demos/benchmark/assets/img_benchmark_cogwheel_alpha256.c \
    lvgl/demos/benchmark/assets/img_benchmark_cogwheel_argb.c \
    lvgl/demos/benchmark/assets/img_benchmark_cogwheel_indexed16.c \
    lvgl/demos/benchmark/assets/img_benchmark_cogwheel_rgb.c \
    lvgl/demos/benchmark/assets/lv_font_benchmark_montserrat_12_compr_az.c.c \
    lvgl/demos/benchmark/assets/lv_font_benchmark_montserrat_16_compr_az.c.c \
    lvgl/demos/benchmark/assets/lv_font_benchmark_montserrat_28_compr_az.c.c \
    lvgl/demos/benchmark/lv_demo_benchmark.c \
    lvgl/demos/flex_layout/lv_demo_flex_layout_ctrl_pad.c \
    lvgl/demos/flex_layout/lv_demo_flex_layout_flex_loader.c \
    lvgl/demos/flex_layout/lv_demo_flex_layout_main.c \
    lvgl/demos/flex_layout/lv_demo_flex_layout_view.c \
    lvgl/demos/flex_layout/lv_demo_flex_layout_view_child_node.c \
    lvgl/demos/flex_layout/lv_demo_flex_layout_view_ctrl_pad.c \
    lvgl/demos/keypad_encoder/lv_demo_keypad_encoder.c \
    lvgl/demos/lv_demos.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_1.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_10.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_11.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_12.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_13.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_14.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_15.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_16.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_17.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_18.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_19.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_2.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_22.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_25.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_3.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_4.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_5.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_6.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_7.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_8.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_9.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_artist_palette.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_books.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_camera_with_flash.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_cat_face.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_deciduous_tree.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_dog_face.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_earth_globe_europe_africa.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_flexed_biceps.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_movie_camera.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_red_heart.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_rocket.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_soccer_ball.c \
    lvgl/demos/multilang/assets/fonts/font_multilang_large.c \
    lvgl/demos/multilang/assets/fonts/font_multilang_small.c \
    lvgl/demos/multilang/assets/img_multilang_like.c \
    lvgl/demos/multilang/lv_demo_multilang.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_corner_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_list_pause.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_list_pause_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_list_play.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_list_play_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_loop.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_loop_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_next.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_next_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_pause.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_pause_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_play.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_play_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_prev.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_prev_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_rnd.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_rnd_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_corner_left.c \
    lvgl/demos/music/assets/img_lv_demo_music_corner_left_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_corner_right.c \
    lvgl/demos/music/assets/img_lv_demo_music_corner_right_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_cover_1.c \
    lvgl/demos/music/assets/img_lv_demo_music_cover_1_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_cover_2.c \
    lvgl/demos/music/assets/img_lv_demo_music_cover_2_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_cover_3.c \
    lvgl/demos/music/assets/img_lv_demo_music_cover_3_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_icon_1.c \
    lvgl/demos/music/assets/img_lv_demo_music_icon_1_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_icon_2.c \
    lvgl/demos/music/assets/img_lv_demo_music_icon_2_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_icon_3.c \
    lvgl/demos/music/assets/img_lv_demo_music_icon_3_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_icon_4.c \
    lvgl/demos/music/assets/img_lv_demo_music_icon_4_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_list_border.c \
    lvgl/demos/music/assets/img_lv_demo_music_list_border_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_logo.c \
    lvgl/demos/music/assets/img_lv_demo_music_slider_knob.c \
    lvgl/demos/music/assets/img_lv_demo_music_slider_knob_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_wave_bottom.c \
    lvgl/demos/music/assets/img_lv_demo_music_wave_bottom_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_wave_top.c \
    lvgl/demos/music/assets/img_lv_demo_music_wave_top_large.c \
    lvgl/demos/music/lv_demo_music.c \
    lvgl/demos/music/lv_demo_music_list.c \
    lvgl/demos/music/lv_demo_music_main.c \
    lvgl/demos/render/assets/img_render_arc_bg.c \
    lvgl/demos/render/assets/img_render_lvgl_logo_argb8888.c \
    lvgl/demos/render/assets/img_render_lvgl_logo_i1.c \
    lvgl/demos/render/assets/img_render_lvgl_logo_l8.c \
    lvgl/demos/render/assets/img_render_lvgl_logo_rgb565.c \
    lvgl/demos/render/assets/img_render_lvgl_logo_rgb888.c \
    lvgl/demos/render/assets/img_render_lvgl_logo_xrgb8888.c \
    lvgl/demos/render/lv_demo_render.c \
    lvgl/demos/scroll/lv_demo_scroll.c \
    lvgl/demos/stress/lv_demo_stress.c \
    lvgl/demos/transform/assets/img_transform_avatar_15.c \
    lvgl/demos/transform/lv_demo_transform.c \
    lvgl/demos/vector_graphic/assets/img_demo_vector_avatar.c \
    lvgl/demos/vector_graphic/lv_demo_vector_graphic.c \
    lvgl/demos/widgets/assets/img_clothes.c \
    lvgl/demos/widgets/assets/img_demo_widgets_avatar.c \
    lvgl/demos/widgets/assets/img_demo_widgets_needle.c \
    lvgl/demos/widgets/assets/img_lvgl_logo.c \
    lvgl/demos/widgets/lv_demo_widgets.c \
    lvgl/examples/anim/lv_example_anim_1.c \
    lvgl/examples/anim/lv_example_anim_2.c \
    lvgl/examples/anim/lv_example_anim_3.c \
    lvgl/examples/anim/lv_example_anim_timeline_1.c \
    lvgl/examples/assets/animimg001.c \
    lvgl/examples/assets/animimg002.c \
    lvgl/examples/assets/animimg003.c \
    lvgl/examples/assets/emoji/img_emoji_F617.c \
    lvgl/examples/assets/img_caret_down.c \
    lvgl/examples/assets/img_cogwheel_argb.c \
    lvgl/examples/assets/img_cogwheel_indexed16.c \
    lvgl/examples/assets/img_cogwheel_rgb.c \
    lvgl/examples/assets/img_hand.c \
    lvgl/examples/assets/img_skew_strip.c \
    lvgl/examples/assets/img_star.c \
    lvgl/examples/assets/imgbtn_left.c \
    lvgl/examples/assets/imgbtn_mid.c \
    lvgl/examples/assets/imgbtn_right.c \
    lvgl/examples/event/lv_example_event_1.c \
    lvgl/examples/event/lv_example_event_2.c \
    lvgl/examples/event/lv_example_event_3.c \
    lvgl/examples/event/lv_example_event_4.c \
    lvgl/examples/get_started/lv_example_get_started_1.c \
    lvgl/examples/get_started/lv_example_get_started_2.c \
    lvgl/examples/get_started/lv_example_get_started_3.c \
    lvgl/examples/get_started/lv_example_get_started_4.c \
    lvgl/examples/layouts/flex/lv_example_flex_1.c \
    lvgl/examples/layouts/flex/lv_example_flex_2.c \
    lvgl/examples/layouts/flex/lv_example_flex_3.c \
    lvgl/examples/layouts/flex/lv_example_flex_4.c \
    lvgl/examples/layouts/flex/lv_example_flex_5.c \
    lvgl/examples/layouts/flex/lv_example_flex_6.c \
    lvgl/examples/layouts/grid/lv_example_grid_1.c \
    lvgl/examples/layouts/grid/lv_example_grid_2.c \
    lvgl/examples/layouts/grid/lv_example_grid_3.c \
    lvgl/examples/layouts/grid/lv_example_grid_4.c \
    lvgl/examples/layouts/grid/lv_example_grid_5.c \
    lvgl/examples/layouts/grid/lv_example_grid_6.c \
    lvgl/examples/libs/barcode/lv_example_barcode_1.c \
    lvgl/examples/libs/bmp/lv_example_bmp_1.c \
    lvgl/examples/libs/ffmpeg/lv_example_ffmpeg_1.c \
    lvgl/examples/libs/ffmpeg/lv_example_ffmpeg_2.c \
    lvgl/examples/libs/freetype/lv_example_freetype_1.c \
    lvgl/examples/libs/gif/img_bulb_gif.c \
    lvgl/examples/libs/gif/lv_example_gif_1.c \
    lvgl/examples/libs/libjpeg_turbo/lv_example_libjpeg_turbo_1.c \
    lvgl/examples/libs/libpng/img_png_demo.c \
    lvgl/examples/libs/libpng/lv_example_libpng_1.c \
    lvgl/examples/libs/lodepng/img_wink_png.c \
    lvgl/examples/libs/lodepng/lv_example_lodepng_1.c \
    lvgl/examples/libs/qrcode/lv_example_qrcode_1.c \
    lvgl/examples/libs/rlottie/lv_example_rlottie_1.c \
    lvgl/examples/libs/rlottie/lv_example_rlottie_2.c \
    lvgl/examples/libs/rlottie/lv_example_rlottie_approve.c \
    lvgl/examples/libs/tiny_ttf/lv_example_tiny_ttf_1.c \
    lvgl/examples/libs/tiny_ttf/lv_example_tiny_ttf_2.c \
    lvgl/examples/libs/tiny_ttf/lv_example_tiny_ttf_3.c \
    lvgl/examples/libs/tiny_ttf/ubuntu_font.c \
    lvgl/examples/libs/tjpgd/lv_example_tjpgd_1.c \
    lvgl/examples/others/file_explorer/lv_example_file_explorer_1.c \
    lvgl/examples/others/file_explorer/lv_example_file_explorer_2.c \
    lvgl/examples/others/file_explorer/lv_example_file_explorer_3.c \
    lvgl/examples/others/fragment/lv_example_fragment_1.c \
    lvgl/examples/others/fragment/lv_example_fragment_2.c \
    lvgl/examples/others/gridnav/lv_example_gridnav_1.c \
    lvgl/examples/others/gridnav/lv_example_gridnav_2.c \
    lvgl/examples/others/gridnav/lv_example_gridnav_3.c \
    lvgl/examples/others/gridnav/lv_example_gridnav_4.c \
    lvgl/examples/others/gridnav/lv_example_gridnav_5.c \
    lvgl/examples/others/ime/lv_example_ime_pinyin_1.c \
    lvgl/examples/others/ime/lv_example_ime_pinyin_2.c \
    lvgl/examples/others/imgfont/lv_example_imgfont_1.c \
    lvgl/examples/others/monkey/lv_example_monkey_1.c \
    lvgl/examples/others/monkey/lv_example_monkey_2.c \
    lvgl/examples/others/monkey/lv_example_monkey_3.c \
    lvgl/examples/others/observer/lv_example_observer_1.c \
    lvgl/examples/others/observer/lv_example_observer_2.c \
    lvgl/examples/others/observer/lv_example_observer_3.c \
    lvgl/examples/others/observer/lv_example_observer_4.c \
    lvgl/examples/others/observer/lv_example_observer_5.c \
    lvgl/examples/others/observer/lv_example_observer_6.c \
    lvgl/examples/others/snapshot/lv_example_snapshot_1.c \
    lvgl/examples/porting/lv_port_disp_template.c \
    lvgl/examples/porting/lv_port_fs_template.c \
    lvgl/examples/porting/lv_port_indev_template.c \
    lvgl/examples/porting/lv_port_lcd_stm32_template.c \
    lvgl/examples/porting/osal/lv_example_osal.c \
    lvgl/examples/scroll/lv_example_scroll_1.c \
    lvgl/examples/scroll/lv_example_scroll_2.c \
    lvgl/examples/scroll/lv_example_scroll_3.c \
    lvgl/examples/scroll/lv_example_scroll_4.c \
    lvgl/examples/scroll/lv_example_scroll_5.c \
    lvgl/examples/scroll/lv_example_scroll_6.c \
    lvgl/examples/styles/lv_example_style_1.c \
    lvgl/examples/styles/lv_example_style_10.c \
    lvgl/examples/styles/lv_example_style_11.c \
    lvgl/examples/styles/lv_example_style_12.c \
    lvgl/examples/styles/lv_example_style_13.c \
    lvgl/examples/styles/lv_example_style_14.c \
    lvgl/examples/styles/lv_example_style_15.c \
    lvgl/examples/styles/lv_example_style_16.c \
    lvgl/examples/styles/lv_example_style_17.c \
    lvgl/examples/styles/lv_example_style_18.c \
    lvgl/examples/styles/lv_example_style_2.c \
    lvgl/examples/styles/lv_example_style_3.c \
    lvgl/examples/styles/lv_example_style_4.c \
    lvgl/examples/styles/lv_example_style_5.c \
    lvgl/examples/styles/lv_example_style_6.c \
    lvgl/examples/styles/lv_example_style_7.c \
    lvgl/examples/styles/lv_example_style_8.c \
    lvgl/examples/styles/lv_example_style_9.c \
    lvgl/examples/widgets/animimg/lv_example_animimg_1.c \
    lvgl/examples/widgets/arc/lv_example_arc_1.c \
    lvgl/examples/widgets/arc/lv_example_arc_2.c \
    lvgl/examples/widgets/bar/lv_example_bar_1.c \
    lvgl/examples/widgets/bar/lv_example_bar_2.c \
    lvgl/examples/widgets/bar/lv_example_bar_3.c \
    lvgl/examples/widgets/bar/lv_example_bar_4.c \
    lvgl/examples/widgets/bar/lv_example_bar_5.c \
    lvgl/examples/widgets/bar/lv_example_bar_6.c \
    lvgl/examples/widgets/bar/lv_example_bar_7.c \
    lvgl/examples/widgets/button/lv_example_button_1.c \
    lvgl/examples/widgets/button/lv_example_button_2.c \
    lvgl/examples/widgets/button/lv_example_button_3.c \
    lvgl/examples/widgets/buttonmatrix/lv_example_buttonmatrix_1.c \
    lvgl/examples/widgets/buttonmatrix/lv_example_buttonmatrix_2.c \
    lvgl/examples/widgets/buttonmatrix/lv_example_buttonmatrix_3.c \
    lvgl/examples/widgets/calendar/lv_example_calendar_1.c \
    lvgl/examples/widgets/calendar/lv_example_calendar_2.c \
    lvgl/examples/widgets/canvas/lv_example_canvas_1.c \
    lvgl/examples/widgets/canvas/lv_example_canvas_2.c \
    lvgl/examples/widgets/canvas/lv_example_canvas_3.c \
    lvgl/examples/widgets/canvas/lv_example_canvas_4.c \
    lvgl/examples/widgets/canvas/lv_example_canvas_5.c \
    lvgl/examples/widgets/canvas/lv_example_canvas_6.c \
    lvgl/examples/widgets/canvas/lv_example_canvas_7.c \
    lvgl/examples/widgets/canvas/lv_example_canvas_8.c \
    lvgl/examples/widgets/chart/lv_example_chart_1.c \
    lvgl/examples/widgets/chart/lv_example_chart_2.c \
    lvgl/examples/widgets/chart/lv_example_chart_3.c \
    lvgl/examples/widgets/chart/lv_example_chart_4.c \
    lvgl/examples/widgets/chart/lv_example_chart_5.c \
    lvgl/examples/widgets/chart/lv_example_chart_6.c \
    lvgl/examples/widgets/chart/lv_example_chart_7.c \
    lvgl/examples/widgets/chart/lv_example_chart_8.c \
    lvgl/examples/widgets/checkbox/lv_example_checkbox_1.c \
    lvgl/examples/widgets/checkbox/lv_example_checkbox_2.c \
    lvgl/examples/widgets/dropdown/lv_example_dropdown_1.c \
    lvgl/examples/widgets/dropdown/lv_example_dropdown_2.c \
    lvgl/examples/widgets/dropdown/lv_example_dropdown_3.c \
    lvgl/examples/widgets/image/lv_example_image_1.c \
    lvgl/examples/widgets/image/lv_example_image_2.c \
    lvgl/examples/widgets/image/lv_example_image_3.c \
    lvgl/examples/widgets/image/lv_example_image_4.c \
    lvgl/examples/widgets/imagebutton/lv_example_imagebutton_1.c \
    lvgl/examples/widgets/keyboard/lv_example_keyboard_1.c \
    lvgl/examples/widgets/keyboard/lv_example_keyboard_2.c \
    lvgl/examples/widgets/label/lv_example_label_1.c \
    lvgl/examples/widgets/label/lv_example_label_2.c \
    lvgl/examples/widgets/label/lv_example_label_3.c \
    lvgl/examples/widgets/label/lv_example_label_4.c \
    lvgl/examples/widgets/label/lv_example_label_5.c \
    lvgl/examples/widgets/led/lv_example_led_1.c \
    lvgl/examples/widgets/line/lv_example_line_1.c \
    lvgl/examples/widgets/list/lv_example_list_1.c \
    lvgl/examples/widgets/list/lv_example_list_2.c \
    lvgl/examples/widgets/lottie/lv_example_lottie_1.c \
    lvgl/examples/widgets/lottie/lv_example_lottie_2.c \
    lvgl/examples/widgets/lottie/lv_example_lottie_approve.c \
    lvgl/examples/widgets/menu/lv_example_menu_1.c \
    lvgl/examples/widgets/menu/lv_example_menu_2.c \
    lvgl/examples/widgets/menu/lv_example_menu_3.c \
    lvgl/examples/widgets/menu/lv_example_menu_4.c \
    lvgl/examples/widgets/menu/lv_example_menu_5.c \
    lvgl/examples/widgets/msgbox/lv_example_msgbox_1.c \
    lvgl/examples/widgets/msgbox/lv_example_msgbox_2.c \
    lvgl/examples/widgets/obj/lv_example_obj_1.c \
    lvgl/examples/widgets/obj/lv_example_obj_2.c \
    lvgl/examples/widgets/roller/lv_example_roller_1.c \
    lvgl/examples/widgets/roller/lv_example_roller_2.c \
    lvgl/examples/widgets/roller/lv_example_roller_3.c \
    lvgl/examples/widgets/scale/lv_example_scale_1.c \
    lvgl/examples/widgets/scale/lv_example_scale_2.c \
    lvgl/examples/widgets/scale/lv_example_scale_3.c \
    lvgl/examples/widgets/scale/lv_example_scale_4.c \
    lvgl/examples/widgets/scale/lv_example_scale_5.c \
    lvgl/examples/widgets/scale/lv_example_scale_6.c \
    lvgl/examples/widgets/scale/lv_example_scale_7.c \
    lvgl/examples/widgets/slider/lv_example_slider_1.c \
    lvgl/examples/widgets/slider/lv_example_slider_2.c \
    lvgl/examples/widgets/slider/lv_example_slider_3.c \
    lvgl/examples/widgets/slider/lv_example_slider_4.c \
    lvgl/examples/widgets/span/lv_example_span_1.c \
    lvgl/examples/widgets/spinbox/lv_example_spinbox_1.c \
    lvgl/examples/widgets/spinner/lv_example_spinner_1.c \
    lvgl/examples/widgets/switch/lv_example_switch_1.c \
    lvgl/examples/widgets/table/lv_example_table_1.c \
    lvgl/examples/widgets/table/lv_example_table_2.c \
    lvgl/examples/widgets/tabview/lv_example_tabview_1.c \
    lvgl/examples/widgets/tabview/lv_example_tabview_2.c \
    lvgl/examples/widgets/textarea/lv_example_textarea_1.c \
    lvgl/examples/widgets/textarea/lv_example_textarea_2.c \
    lvgl/examples/widgets/textarea/lv_example_textarea_3.c \
    lvgl/examples/widgets/tileview/lv_example_tileview_1.c \
    lvgl/examples/widgets/win/lv_example_win_1.c \
    lvgl/src/core/lv_group.c \
    lvgl/src/core/lv_obj.c \
    lvgl/src/core/lv_obj_class.c \
    lvgl/src/core/lv_obj_draw.c \
    lvgl/src/core/lv_obj_event.c \
    lvgl/src/core/lv_obj_id_builtin.c \
    lvgl/src/core/lv_obj_pos.c \
    lvgl/src/core/lv_obj_property.c \
    lvgl/src/core/lv_obj_scroll.c \
    lvgl/src/core/lv_obj_style.c \
    lvgl/src/core/lv_obj_style_gen.c \
    lvgl/src/core/lv_obj_tree.c \
    lvgl/src/core/lv_refr.c \
    lvgl/src/display/lv_display.c \
    lvgl/src/draw/lv_draw.c \
    lvgl/src/draw/lv_draw_arc.c \
    lvgl/src/draw/lv_draw_buf.c \
    lvgl/src/draw/lv_draw_image.c \
    lvgl/src/draw/lv_draw_label.c \
    lvgl/src/draw/lv_draw_line.c \
    lvgl/src/draw/lv_draw_mask.c \
    lvgl/src/draw/lv_draw_rect.c \
    lvgl/src/draw/lv_draw_triangle.c \
    lvgl/src/draw/lv_draw_vector.c \
    lvgl/src/draw/lv_image_decoder.c \
    lvgl/src/draw/nxp/pxp/lv_draw_buf_pxp.c \
    lvgl/src/draw/nxp/pxp/lv_draw_pxp.c \
    lvgl/src/draw/nxp/pxp/lv_draw_pxp_fill.c \
    lvgl/src/draw/nxp/pxp/lv_draw_pxp_img.c \
    lvgl/src/draw/nxp/pxp/lv_draw_pxp_layer.c \
    lvgl/src/draw/nxp/pxp/lv_pxp_cfg.c \
    lvgl/src/draw/nxp/pxp/lv_pxp_osa.c \
    lvgl/src/draw/nxp/pxp/lv_pxp_utils.c \
    lvgl/src/draw/nxp/vglite/lv_draw_buf_vglite.c \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite.c \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite_arc.c \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite_border.c \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite_fill.c \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite_img.c \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite_label.c \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite_layer.c \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite_line.c \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite_triangle.c \
    lvgl/src/draw/nxp/vglite/lv_vglite_buf.c \
    lvgl/src/draw/nxp/vglite/lv_vglite_matrix.c \
    lvgl/src/draw/nxp/vglite/lv_vglite_path.c \
    lvgl/src/draw/nxp/vglite/lv_vglite_utils.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_arc.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_border.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_fill.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_image.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_label.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_line.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_mask_rectangle.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_triangle.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_utils.c \
    lvgl/src/draw/sdl/lv_draw_sdl.c \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend.c \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_al88.c \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_argb8888.c \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_i1.c \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_l8.c \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_rgb565.c \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_rgb888.c \
    lvgl/src/draw/sw/lv_draw_sw.c \
    lvgl/src/draw/sw/lv_draw_sw_arc.c \
    lvgl/src/draw/sw/lv_draw_sw_border.c \
    lvgl/src/draw/sw/lv_draw_sw_box_shadow.c \
    lvgl/src/draw/sw/lv_draw_sw_fill.c \
    lvgl/src/draw/sw/lv_draw_sw_gradient.c \
    lvgl/src/draw/sw/lv_draw_sw_img.c \
    lvgl/src/draw/sw/lv_draw_sw_letter.c \
    lvgl/src/draw/sw/lv_draw_sw_line.c \
    lvgl/src/draw/sw/lv_draw_sw_mask.c \
    lvgl/src/draw/sw/lv_draw_sw_mask_rect.c \
    lvgl/src/draw/sw/lv_draw_sw_transform.c \
    lvgl/src/draw/sw/lv_draw_sw_triangle.c \
    lvgl/src/draw/sw/lv_draw_sw_vector.c \
    lvgl/src/draw/vg_lite/lv_draw_buf_vg_lite.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_arc.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_border.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_box_shadow.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_fill.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_img.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_label.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_layer.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_line.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_mask_rect.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_triangle.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_vector.c \
    lvgl/src/draw/vg_lite/lv_vg_lite_decoder.c \
    lvgl/src/draw/vg_lite/lv_vg_lite_grad.c \
    lvgl/src/draw/vg_lite/lv_vg_lite_math.c \
    lvgl/src/draw/vg_lite/lv_vg_lite_path.c \
    lvgl/src/draw/vg_lite/lv_vg_lite_pending.c \
    lvgl/src/draw/vg_lite/lv_vg_lite_stroke.c \
    lvgl/src/draw/vg_lite/lv_vg_lite_utils.c \
    lvgl/src/drivers/display/drm/lv_linux_drm.c \
    lvgl/src/drivers/display/fb/lv_linux_fbdev.c \
    lvgl/src/drivers/display/ili9341/lv_ili9341.c \
    lvgl/src/drivers/display/lcd/lv_lcd_generic_mipi.c \
    lvgl/src/drivers/display/renesas_glcdc/lv_renesas_glcdc.c \
    lvgl/src/drivers/display/st7735/lv_st7735.c \
    lvgl/src/drivers/display/st7789/lv_st7789.c \
    lvgl/src/drivers/display/st7796/lv_st7796.c \
    lvgl/src/drivers/display/tft_espi/lv_tft_espi.cpp \
    lvgl/src/drivers/evdev/lv_evdev.c \
    lvgl/src/drivers/glfw/lv_glfw_window.c \
    lvgl/src/drivers/glfw/lv_opengles_debug.c \
    lvgl/src/drivers/glfw/lv_opengles_driver.c \
    lvgl/src/drivers/glfw/lv_opengles_texture.c \
    lvgl/src/drivers/libinput/lv_libinput.c \
    lvgl/src/drivers/libinput/lv_xkb.c \
    lvgl/src/drivers/nuttx/lv_nuttx_cache.c \
    lvgl/src/drivers/nuttx/lv_nuttx_entry.c \
    lvgl/src/drivers/nuttx/lv_nuttx_fbdev.c \
    lvgl/src/drivers/nuttx/lv_nuttx_image_cache.c \
    lvgl/src/drivers/nuttx/lv_nuttx_lcd.c \
    lvgl/src/drivers/nuttx/lv_nuttx_libuv.c \
    lvgl/src/drivers/nuttx/lv_nuttx_profiler.c \
    lvgl/src/drivers/nuttx/lv_nuttx_touchscreen.c \
    lvgl/src/drivers/qnx/lv_qnx.c \
    lvgl/src/drivers/sdl/lv_sdl_keyboard.c \
    lvgl/src/drivers/sdl/lv_sdl_mouse.c \
    lvgl/src/drivers/sdl/lv_sdl_mousewheel.c \
    lvgl/src/drivers/sdl/lv_sdl_window.c \
    lvgl/src/drivers/wayland/lv_wayland.c \
    lvgl/src/drivers/wayland/lv_wayland_smm.c \
    lvgl/src/drivers/windows/lv_windows_context.c \
    lvgl/src/drivers/windows/lv_windows_display.c \
    lvgl/src/drivers/windows/lv_windows_input.c \
    lvgl/src/drivers/x11/lv_x11_display.c \
    lvgl/src/drivers/x11/lv_x11_input.c \
    lvgl/src/font/lv_binfont_loader.c \
    lvgl/src/font/lv_font.c \
    lvgl/src/font/lv_font_dejavu_16_persian_hebrew.c \
    lvgl/src/font/lv_font_fmt_txt.c \
    lvgl/src/font/lv_font_montserrat_10.c \
    lvgl/src/font/lv_font_montserrat_12.c \
    lvgl/src/font/lv_font_montserrat_14.c \
    lvgl/src/font/lv_font_montserrat_16.c \
    lvgl/src/font/lv_font_montserrat_18.c \
    lvgl/src/font/lv_font_montserrat_20.c \
    lvgl/src/font/lv_font_montserrat_22.c \
    lvgl/src/font/lv_font_montserrat_24.c \
    lvgl/src/font/lv_font_montserrat_26.c \
    lvgl/src/font/lv_font_montserrat_28.c \
    lvgl/src/font/lv_font_montserrat_28_compressed.c \
    lvgl/src/font/lv_font_montserrat_30.c \
    lvgl/src/font/lv_font_montserrat_32.c \
    lvgl/src/font/lv_font_montserrat_34.c \
    lvgl/src/font/lv_font_montserrat_36.c \
    lvgl/src/font/lv_font_montserrat_38.c \
    lvgl/src/font/lv_font_montserrat_40.c \
    lvgl/src/font/lv_font_montserrat_42.c \
    lvgl/src/font/lv_font_montserrat_44.c \
    lvgl/src/font/lv_font_montserrat_46.c \
    lvgl/src/font/lv_font_montserrat_48.c \
    lvgl/src/font/lv_font_montserrat_8.c \
    lvgl/src/font/lv_font_simsun_14_cjk.c \
    lvgl/src/font/lv_font_simsun_16_cjk.c \
    lvgl/src/font/lv_font_unscii_16.c \
    lvgl/src/font/lv_font_unscii_8.c \
    lvgl/src/indev/lv_indev.c \
    lvgl/src/indev/lv_indev_scroll.c \
    lvgl/src/layouts/flex/lv_flex.c \
    lvgl/src/layouts/grid/lv_grid.c \
    lvgl/src/layouts/lv_layout.c \
    lvgl/src/libs/barcode/code128.c \
    lvgl/src/libs/barcode/lv_barcode.c \
    lvgl/src/libs/bin_decoder/lv_bin_decoder.c \
    lvgl/src/libs/bmp/lv_bmp.c \
    lvgl/src/libs/ffmpeg/lv_ffmpeg.c \
    lvgl/src/libs/freetype/lv_freetype.c \
    lvgl/src/libs/freetype/lv_freetype_glyph.c \
    lvgl/src/libs/freetype/lv_freetype_image.c \
    lvgl/src/libs/freetype/lv_freetype_outline.c \
    lvgl/src/libs/freetype/lv_ftsystem.c \
    lvgl/src/libs/fsdrv/lv_fs_arduino_esp_littlefs.cpp \
    lvgl/src/libs/fsdrv/lv_fs_arduino_sd.cpp \
    lvgl/src/libs/fsdrv/lv_fs_cbfs.c \
    lvgl/src/libs/fsdrv/lv_fs_fatfs.c \
    lvgl/src/libs/fsdrv/lv_fs_littlefs.c \
    lvgl/src/libs/fsdrv/lv_fs_memfs.c \
    lvgl/src/libs/fsdrv/lv_fs_posix.c \
    lvgl/src/libs/fsdrv/lv_fs_stdio.c \
    lvgl/src/libs/fsdrv/lv_fs_win32.c \
    lvgl/src/libs/gif/gifdec.c \
    lvgl/src/libs/gif/lv_gif.c \
    lvgl/src/libs/libjpeg_turbo/lv_libjpeg_turbo.c \
    lvgl/src/libs/libpng/lv_libpng.c \
    lvgl/src/libs/lodepng/lodepng.c \
    lvgl/src/libs/lodepng/lv_lodepng.c \
    lvgl/src/libs/lz4/lz4.c \
    lvgl/src/libs/qrcode/lv_qrcode.c \
    lvgl/src/libs/qrcode/qrcodegen.c \
    lvgl/src/libs/rle/lv_rle.c \
    lvgl/src/libs/rlottie/lv_rlottie.c \
    lvgl/src/libs/thorvg/tvgAccessor.cpp \
    lvgl/src/libs/thorvg/tvgAnimation.cpp \
    lvgl/src/libs/thorvg/tvgCanvas.cpp \
    lvgl/src/libs/thorvg/tvgCapi.cpp \
    lvgl/src/libs/thorvg/tvgCompressor.cpp \
    lvgl/src/libs/thorvg/tvgFill.cpp \
    lvgl/src/libs/thorvg/tvgGlCanvas.cpp \
    lvgl/src/libs/thorvg/tvgInitializer.cpp \
    lvgl/src/libs/thorvg/tvgLines.cpp \
    lvgl/src/libs/thorvg/tvgLoader.cpp \
    lvgl/src/libs/thorvg/tvgLottieAnimation.cpp \
    lvgl/src/libs/thorvg/tvgLottieBuilder.cpp \
    lvgl/src/libs/thorvg/tvgLottieExpressions.cpp \
    lvgl/src/libs/thorvg/tvgLottieInterpolator.cpp \
    lvgl/src/libs/thorvg/tvgLottieLoader.cpp \
    lvgl/src/libs/thorvg/tvgLottieModel.cpp \
    lvgl/src/libs/thorvg/tvgLottieParser.cpp \
    lvgl/src/libs/thorvg/tvgLottieParserHandler.cpp \
    lvgl/src/libs/thorvg/tvgMath.cpp \
    lvgl/src/libs/thorvg/tvgPaint.cpp \
    lvgl/src/libs/thorvg/tvgPicture.cpp \
    lvgl/src/libs/thorvg/tvgRawLoader.cpp \
    lvgl/src/libs/thorvg/tvgRender.cpp \
    lvgl/src/libs/thorvg/tvgSaver.cpp \
    lvgl/src/libs/thorvg/tvgScene.cpp \
    lvgl/src/libs/thorvg/tvgShape.cpp \
    lvgl/src/libs/thorvg/tvgStr.cpp \
    lvgl/src/libs/thorvg/tvgSvgCssStyle.cpp \
    lvgl/src/libs/thorvg/tvgSvgLoader.cpp \
    lvgl/src/libs/thorvg/tvgSvgPath.cpp \
    lvgl/src/libs/thorvg/tvgSvgSceneBuilder.cpp \
    lvgl/src/libs/thorvg/tvgSvgUtil.cpp \
    lvgl/src/libs/thorvg/tvgSwCanvas.cpp \
    lvgl/src/libs/thorvg/tvgSwFill.cpp \
    lvgl/src/libs/thorvg/tvgSwImage.cpp \
    lvgl/src/libs/thorvg/tvgSwMath.cpp \
    lvgl/src/libs/thorvg/tvgSwMemPool.cpp \
    lvgl/src/libs/thorvg/tvgSwRaster.cpp \
    lvgl/src/libs/thorvg/tvgSwRenderer.cpp \
    lvgl/src/libs/thorvg/tvgSwRle.cpp \
    lvgl/src/libs/thorvg/tvgSwShape.cpp \
    lvgl/src/libs/thorvg/tvgSwStroke.cpp \
    lvgl/src/libs/thorvg/tvgTaskScheduler.cpp \
    lvgl/src/libs/thorvg/tvgText.cpp \
    lvgl/src/libs/thorvg/tvgWgCanvas.cpp \
    lvgl/src/libs/thorvg/tvgXmlParser.cpp \
    lvgl/src/libs/tiny_ttf/lv_tiny_ttf.c \
    lvgl/src/libs/tjpgd/lv_tjpgd.c \
    lvgl/src/libs/tjpgd/tjpgd.c \
    lvgl/src/lv_init.c \
    lvgl/src/misc/cache/lv_cache.c \
    lvgl/src/misc/cache/lv_cache_entry.c \
    lvgl/src/misc/cache/lv_cache_lru_rb.c \
    lvgl/src/misc/cache/lv_image_cache.c \
    lvgl/src/misc/cache/lv_image_header_cache.c \
    lvgl/src/misc/lv_anim.c \
    lvgl/src/misc/lv_anim_timeline.c \
    lvgl/src/misc/lv_area.c \
    lvgl/src/misc/lv_array.c \
    lvgl/src/misc/lv_async.c \
    lvgl/src/misc/lv_bidi.c \
    lvgl/src/misc/lv_color.c \
    lvgl/src/misc/lv_color_op.c \
    lvgl/src/misc/lv_event.c \
    lvgl/src/misc/lv_fs.c \
    lvgl/src/misc/lv_ll.c \
    lvgl/src/misc/lv_log.c \
    lvgl/src/misc/lv_lru.c \
    lvgl/src/misc/lv_math.c \
    lvgl/src/misc/lv_matrix.c \
    lvgl/src/misc/lv_palette.c \
    lvgl/src/misc/lv_profiler_builtin.c \
    lvgl/src/misc/lv_rb.c \
    lvgl/src/misc/lv_style.c \
    lvgl/src/misc/lv_style_gen.c \
    lvgl/src/misc/lv_templ.c \
    lvgl/src/misc/lv_text.c \
    lvgl/src/misc/lv_text_ap.c \
    lvgl/src/misc/lv_timer.c \
    lvgl/src/misc/lv_utils.c \
    lvgl/src/osal/lv_cmsis_rtos2.c \
    lvgl/src/osal/lv_freertos.c \
    lvgl/src/osal/lv_mqx.c \
    lvgl/src/osal/lv_os.c \
    lvgl/src/osal/lv_os_none.c \
    lvgl/src/osal/lv_pthread.c \
    lvgl/src/osal/lv_rtthread.c \
    lvgl/src/osal/lv_windows.c \
    lvgl/src/others/file_explorer/lv_file_explorer.c \
    lvgl/src/others/fragment/lv_fragment.c \
    lvgl/src/others/fragment/lv_fragment_manager.c \
    lvgl/src/others/gridnav/lv_gridnav.c \
    lvgl/src/others/ime/lv_ime_pinyin.c \
    lvgl/src/others/imgfont/lv_imgfont.c \
    lvgl/src/others/monkey/lv_monkey.c \
    lvgl/src/others/observer/lv_observer.c \
    lvgl/src/others/snapshot/lv_snapshot.c \
    lvgl/src/others/sysmon/lv_sysmon.c \
    lvgl/src/others/vg_lite_tvg/vg_lite_matrix.c \
    lvgl/src/others/vg_lite_tvg/vg_lite_tvg.cpp \
    lvgl/src/stdlib/builtin/lv_mem_core_builtin.c \
    lvgl/src/stdlib/builtin/lv_sprintf_builtin.c \
    lvgl/src/stdlib/builtin/lv_string_builtin.c \
    lvgl/src/stdlib/builtin/lv_tlsf.c \
    lvgl/src/stdlib/clib/lv_mem_core_clib.c \
    lvgl/src/stdlib/clib/lv_sprintf_clib.c \
    lvgl/src/stdlib/clib/lv_string_clib.c \
    lvgl/src/stdlib/lv_mem.c \
    lvgl/src/stdlib/micropython/lv_mem_core_micropython.c \
    lvgl/src/stdlib/rtthread/lv_mem_core_rtthread.c \
    lvgl/src/stdlib/rtthread/lv_sprintf_rtthread.c \
    lvgl/src/stdlib/rtthread/lv_string_rtthread.c \
    lvgl/src/themes/default/lv_theme_default.c \
    lvgl/src/themes/lv_theme.c \
    lvgl/src/themes/mono/lv_theme_mono.c \
    lvgl/src/themes/simple/lv_theme_simple.c \
    lvgl/src/tick/lv_tick.c \
    lvgl/src/widgets/animimage/lv_animimage.c \
    lvgl/src/widgets/arc/lv_arc.c \
    lvgl/src/widgets/bar/lv_bar.c \
    lvgl/src/widgets/button/lv_button.c \
    lvgl/src/widgets/buttonmatrix/lv_buttonmatrix.c \
    lvgl/src/widgets/calendar/lv_calendar.c \
    lvgl/src/widgets/calendar/lv_calendar_chinese.c \
    lvgl/src/widgets/calendar/lv_calendar_header_arrow.c \
    lvgl/src/widgets/calendar/lv_calendar_header_dropdown.c \
    lvgl/src/widgets/canvas/lv_canvas.c \
    lvgl/src/widgets/chart/lv_chart.c \
    lvgl/src/widgets/checkbox/lv_checkbox.c \
    lvgl/src/widgets/dropdown/lv_dropdown.c \
    lvgl/src/widgets/image/lv_image.c \
    lvgl/src/widgets/imagebutton/lv_imagebutton.c \
    lvgl/src/widgets/keyboard/lv_keyboard.c \
    lvgl/src/widgets/label/lv_label.c \
    lvgl/src/widgets/led/lv_led.c \
    lvgl/src/widgets/line/lv_line.c \
    lvgl/src/widgets/list/lv_list.c \
    lvgl/src/widgets/lottie/lv_lottie.c \
    lvgl/src/widgets/menu/lv_menu.c \
    lvgl/src/widgets/msgbox/lv_msgbox.c \
    lvgl/src/widgets/objx_templ/lv_objx_templ.c \
    lvgl/src/widgets/property/lv_dropdown_properties.c \
    lvgl/src/widgets/property/lv_image_properties.c \
    lvgl/src/widgets/property/lv_keyboard_properties.c \
    lvgl/src/widgets/property/lv_label_properties.c \
    lvgl/src/widgets/property/lv_obj_properties.c \
    lvgl/src/widgets/property/lv_roller_properties.c \
    lvgl/src/widgets/property/lv_style_properties.c \
    lvgl/src/widgets/property/lv_textarea_properties.c \
    lvgl/src/widgets/roller/lv_roller.c \
    lvgl/src/widgets/scale/lv_scale.c \
    lvgl/src/widgets/slider/lv_slider.c \
    lvgl/src/widgets/span/lv_span.c \
    lvgl/src/widgets/spinbox/lv_spinbox.c \
    lvgl/src/widgets/spinner/lv_spinner.c \
    lvgl/src/widgets/switch/lv_switch.c \
    lvgl/src/widgets/table/lv_table.c \
    lvgl/src/widgets/tabview/lv_tabview.c \
    lvgl/src/widgets/textarea/lv_textarea.c \
    lvgl/src/widgets/tileview/lv_tileview.c \
    lvgl/src/widgets/win/lv_win.c \
    main.cpp

HEADERS += \
    app/app_ui.h \
    app/lv_conf.h \
    app/mainwindow.h \
    hal/clabel.h \
    hal/lvgl_hal.h \
    lvgl/demos/benchmark/lv_demo_benchmark.h \
    lvgl/demos/flex_layout/lv_demo_flex_layout.h \
    lvgl/demos/flex_layout/lv_demo_flex_layout_main.h \
    lvgl/demos/keypad_encoder/lv_demo_keypad_encoder.h \
    lvgl/demos/lv_demos.h \
    lvgl/demos/multilang/lv_demo_multilang.h \
    lvgl/demos/music/assets/spectrum_1.h \
    lvgl/demos/music/assets/spectrum_2.h \
    lvgl/demos/music/assets/spectrum_3.h \
    lvgl/demos/music/lv_demo_music.h \
    lvgl/demos/music/lv_demo_music_list.h \
    lvgl/demos/music/lv_demo_music_main.h \
    lvgl/demos/render/lv_demo_render.h \
    lvgl/demos/scroll/lv_demo_scroll.h \
    lvgl/demos/stress/lv_demo_stress.h \
    lvgl/demos/transform/lv_demo_transform.h \
    lvgl/demos/vector_graphic/lv_demo_vector_graphic.h \
    lvgl/demos/widgets/lv_demo_widgets.h \
    lvgl/examples/anim/lv_example_anim.h \
    lvgl/examples/arduino/LVGL_Arduino/LVGL_Arduino.ino \
    lvgl/examples/event/lv_example_event.h \
    lvgl/examples/get_started/lv_example_get_started.h \
    lvgl/examples/layouts/flex/lv_example_flex.h \
    lvgl/examples/layouts/grid/lv_example_grid.h \
    lvgl/examples/layouts/lv_example_layout.h \
    lvgl/examples/libs/barcode/lv_example_barcode.h \
    lvgl/examples/libs/bmp/lv_example_bmp.h \
    lvgl/examples/libs/ffmpeg/lv_example_ffmpeg.h \
    lvgl/examples/libs/freetype/lv_example_freetype.h \
    lvgl/examples/libs/gif/lv_example_gif.h \
    lvgl/examples/libs/libjpeg_turbo/lv_example_libjpeg_turbo.h \
    lvgl/examples/libs/libpng/lv_example_libpng.h \
    lvgl/examples/libs/lodepng/lv_example_lodepng.h \
    lvgl/examples/libs/lv_example_libs.h \
    lvgl/examples/libs/qrcode/lv_example_qrcode.h \
    lvgl/examples/libs/rlottie/lv_example_rlottie.h \
    lvgl/examples/libs/tiny_ttf/lv_example_tiny_ttf.h \
    lvgl/examples/libs/tjpgd/lv_example_tjpgd.h \
    lvgl/examples/lv_examples.h \
    lvgl/examples/others/file_explorer/lv_example_file_explorer.h \
    lvgl/examples/others/fragment/lv_example_fragment.h \
    lvgl/examples/others/gridnav/lv_example_gridnav.h \
    lvgl/examples/others/ime/lv_example_ime_pinyin.h \
    lvgl/examples/others/imgfont/lv_example_imgfont.h \
    lvgl/examples/others/lv_example_others.h \
    lvgl/examples/others/monkey/lv_example_monkey.h \
    lvgl/examples/others/observer/lv_example_observer.h \
    lvgl/examples/others/snapshot/lv_example_snapshot.h \
    lvgl/examples/porting/lv_port_disp_template.h \
    lvgl/examples/porting/lv_port_fs_template.h \
    lvgl/examples/porting/lv_port_indev_template.h \
    lvgl/examples/porting/lv_port_lcd_stm32_template.h \
    lvgl/examples/porting/osal/lv_example_osal.h \
    lvgl/examples/scroll/lv_example_scroll.h \
    lvgl/examples/styles/lv_example_style.h \
    lvgl/examples/widgets/lv_example_widgets.h \
    lvgl/lvgl.h \
    lvgl/src/core/lv_global.h \
    lvgl/src/core/lv_group.h \
    lvgl/src/core/lv_group_private.h \
    lvgl/src/core/lv_obj.h \
    lvgl/src/core/lv_obj_class.h \
    lvgl/src/core/lv_obj_class_private.h \
    lvgl/src/core/lv_obj_draw.h \
    lvgl/src/core/lv_obj_draw_private.h \
    lvgl/src/core/lv_obj_event.h \
    lvgl/src/core/lv_obj_event_private.h \
    lvgl/src/core/lv_obj_pos.h \
    lvgl/src/core/lv_obj_private.h \
    lvgl/src/core/lv_obj_property.h \
    lvgl/src/core/lv_obj_scroll.h \
    lvgl/src/core/lv_obj_scroll_private.h \
    lvgl/src/core/lv_obj_style.h \
    lvgl/src/core/lv_obj_style_gen.h \
    lvgl/src/core/lv_obj_style_private.h \
    lvgl/src/core/lv_obj_tree.h \
    lvgl/src/core/lv_refr.h \
    lvgl/src/core/lv_refr_private.h \
    lvgl/src/display/lv_display.h \
    lvgl/src/display/lv_display_private.h \
    lvgl/src/draw/lv_draw.h \
    lvgl/src/draw/lv_draw_arc.h \
    lvgl/src/draw/lv_draw_buf.h \
    lvgl/src/draw/lv_draw_buf_private.h \
    lvgl/src/draw/lv_draw_image.h \
    lvgl/src/draw/lv_draw_image_private.h \
    lvgl/src/draw/lv_draw_label.h \
    lvgl/src/draw/lv_draw_label_private.h \
    lvgl/src/draw/lv_draw_line.h \
    lvgl/src/draw/lv_draw_mask.h \
    lvgl/src/draw/lv_draw_mask_private.h \
    lvgl/src/draw/lv_draw_private.h \
    lvgl/src/draw/lv_draw_rect.h \
    lvgl/src/draw/lv_draw_rect_private.h \
    lvgl/src/draw/lv_draw_triangle.h \
    lvgl/src/draw/lv_draw_triangle_private.h \
    lvgl/src/draw/lv_draw_vector.h \
    lvgl/src/draw/lv_draw_vector_private.h \
    lvgl/src/draw/lv_image_decoder.h \
    lvgl/src/draw/lv_image_decoder_private.h \
    lvgl/src/draw/lv_image_dsc.h \
    lvgl/src/draw/nxp/pxp/lv_draw_pxp.h \
    lvgl/src/draw/nxp/pxp/lv_pxp_cfg.h \
    lvgl/src/draw/nxp/pxp/lv_pxp_osa.h \
    lvgl/src/draw/nxp/pxp/lv_pxp_utils.h \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite.h \
    lvgl/src/draw/nxp/vglite/lv_vglite_buf.h \
    lvgl/src/draw/nxp/vglite/lv_vglite_matrix.h \
    lvgl/src/draw/nxp/vglite/lv_vglite_path.h \
    lvgl/src/draw/nxp/vglite/lv_vglite_utils.h \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d.h \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_utils.h \
    lvgl/src/draw/sdl/lv_draw_sdl.h \
    lvgl/src/draw/sw/arm2d/lv_draw_sw_arm2d.h \
    lvgl/src/draw/sw/arm2d/lv_draw_sw_helium.h \
    lvgl/src/draw/sw/blend/arm2d/lv_blend_arm2d.h \
    lvgl/src/draw/sw/blend/helium/lv_blend_helium.h \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend.h \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend_private.h \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_al88.h \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_argb8888.h \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_i1.h \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_l8.h \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_rgb565.h \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_rgb888.h \
    lvgl/src/draw/sw/blend/neon/lv_blend_neon.h \
    lvgl/src/draw/sw/lv_draw_sw.h \
    lvgl/src/draw/sw/lv_draw_sw_gradient.h \
    lvgl/src/draw/sw/lv_draw_sw_gradient_private.h \
    lvgl/src/draw/sw/lv_draw_sw_mask.h \
    lvgl/src/draw/sw/lv_draw_sw_mask_private.h \
    lvgl/src/draw/sw/lv_draw_sw_private.h \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite.h \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_type.h \
    lvgl/src/draw/vg_lite/lv_vg_lite_decoder.h \
    lvgl/src/draw/vg_lite/lv_vg_lite_grad.h \
    lvgl/src/draw/vg_lite/lv_vg_lite_math.h \
    lvgl/src/draw/vg_lite/lv_vg_lite_path.h \
    lvgl/src/draw/vg_lite/lv_vg_lite_pending.h \
    lvgl/src/draw/vg_lite/lv_vg_lite_stroke.h \
    lvgl/src/draw/vg_lite/lv_vg_lite_utils.h \
    lvgl/src/drivers/display/drm/lv_linux_drm.h \
    lvgl/src/drivers/display/fb/lv_linux_fbdev.h \
    lvgl/src/drivers/display/ili9341/lv_ili9341.h \
    lvgl/src/drivers/display/lcd/lv_lcd_generic_mipi.h \
    lvgl/src/drivers/display/renesas_glcdc/lv_renesas_glcdc.h \
    lvgl/src/drivers/display/st7735/lv_st7735.h \
    lvgl/src/drivers/display/st7789/lv_st7789.h \
    lvgl/src/drivers/display/st7796/lv_st7796.h \
    lvgl/src/drivers/display/tft_espi/lv_tft_espi.h \
    lvgl/src/drivers/evdev/lv_evdev.h \
    lvgl/src/drivers/glfw/lv_glfw_window.h \
    lvgl/src/drivers/glfw/lv_glfw_window_private.h \
    lvgl/src/drivers/glfw/lv_opengles_debug.h \
    lvgl/src/drivers/glfw/lv_opengles_driver.h \
    lvgl/src/drivers/glfw/lv_opengles_texture.h \
    lvgl/src/drivers/libinput/lv_libinput.h \
    lvgl/src/drivers/libinput/lv_libinput_private.h \
    lvgl/src/drivers/libinput/lv_xkb.h \
    lvgl/src/drivers/libinput/lv_xkb_private.h \
    lvgl/src/drivers/lv_drivers.h \
    lvgl/src/drivers/nuttx/lv_nuttx_cache.h \
    lvgl/src/drivers/nuttx/lv_nuttx_entry.h \
    lvgl/src/drivers/nuttx/lv_nuttx_fbdev.h \
    lvgl/src/drivers/nuttx/lv_nuttx_image_cache.h \
    lvgl/src/drivers/nuttx/lv_nuttx_lcd.h \
    lvgl/src/drivers/nuttx/lv_nuttx_libuv.h \
    lvgl/src/drivers/nuttx/lv_nuttx_profiler.h \
    lvgl/src/drivers/nuttx/lv_nuttx_touchscreen.h \
    lvgl/src/drivers/qnx/lv_qnx.h \
    lvgl/src/drivers/sdl/lv_sdl_keyboard.h \
    lvgl/src/drivers/sdl/lv_sdl_mouse.h \
    lvgl/src/drivers/sdl/lv_sdl_mousewheel.h \
    lvgl/src/drivers/sdl/lv_sdl_private.h \
    lvgl/src/drivers/sdl/lv_sdl_window.h \
    lvgl/src/drivers/wayland/lv_wayland.h \
    lvgl/src/drivers/wayland/lv_wayland_smm.h \
    lvgl/src/drivers/windows/lv_windows_context.h \
    lvgl/src/drivers/windows/lv_windows_display.h \
    lvgl/src/drivers/windows/lv_windows_input.h \
    lvgl/src/drivers/windows/lv_windows_input_private.h \
    lvgl/src/drivers/x11/lv_x11.h \
    lvgl/src/font/lv_binfont_loader.h \
    lvgl/src/font/lv_font.h \
    lvgl/src/font/lv_font_fmt_txt.h \
    lvgl/src/font/lv_font_fmt_txt_private.h \
    lvgl/src/font/lv_symbol_def.h \
    lvgl/src/indev/lv_indev.h \
    lvgl/src/indev/lv_indev_private.h \
    lvgl/src/indev/lv_indev_scroll.h \
    lvgl/src/layouts/flex/lv_flex.h \
    lvgl/src/layouts/grid/lv_grid.h \
    lvgl/src/layouts/lv_layout.h \
    lvgl/src/layouts/lv_layout_private.h \
    lvgl/src/libs/barcode/code128.h \
    lvgl/src/libs/barcode/lv_barcode.h \
    lvgl/src/libs/barcode/lv_barcode_private.h \
    lvgl/src/libs/bin_decoder/lv_bin_decoder.h \
    lvgl/src/libs/bmp/lv_bmp.h \
    lvgl/src/libs/ffmpeg/lv_ffmpeg.h \
    lvgl/src/libs/ffmpeg/lv_ffmpeg_private.h \
    lvgl/src/libs/freetype/ftmodule.h \
    lvgl/src/libs/freetype/ftoption.h \
    lvgl/src/libs/freetype/lv_freetype.h \
    lvgl/src/libs/freetype/lv_freetype_private.h \
    lvgl/src/libs/fsdrv/lv_fsdrv.h \
    lvgl/src/libs/gif/gifdec.h \
    lvgl/src/libs/gif/gifdec_mve.h \
    lvgl/src/libs/gif/lv_gif.h \
    lvgl/src/libs/gif/lv_gif_private.h \
    lvgl/src/libs/libjpeg_turbo/lv_libjpeg_turbo.h \
    lvgl/src/libs/libpng/lv_libpng.h \
    lvgl/src/libs/lodepng/lodepng.h \
    lvgl/src/libs/lodepng/lv_lodepng.h \
    lvgl/src/libs/lz4/lz4.h \
    lvgl/src/libs/qrcode/lv_qrcode.h \
    lvgl/src/libs/qrcode/lv_qrcode_private.h \
    lvgl/src/libs/qrcode/qrcodegen.h \
    lvgl/src/libs/rle/lv_rle.h \
    lvgl/src/libs/rlottie/lv_rlottie.h \
    lvgl/src/libs/rlottie/lv_rlottie_private.h \
    lvgl/src/libs/thorvg/config.h \
    lvgl/src/libs/thorvg/rapidjson/allocators.h \
    lvgl/src/libs/thorvg/rapidjson/cursorstreamwrapper.h \
    lvgl/src/libs/thorvg/rapidjson/document.h \
    lvgl/src/libs/thorvg/rapidjson/encodedstream.h \
    lvgl/src/libs/thorvg/rapidjson/encodings.h \
    lvgl/src/libs/thorvg/rapidjson/error/en.h \
    lvgl/src/libs/thorvg/rapidjson/error/error.h \
    lvgl/src/libs/thorvg/rapidjson/filereadstream.h \
    lvgl/src/libs/thorvg/rapidjson/filewritestream.h \
    lvgl/src/libs/thorvg/rapidjson/fwd.h \
    lvgl/src/libs/thorvg/rapidjson/internal/biginteger.h \
    lvgl/src/libs/thorvg/rapidjson/internal/clzll.h \
    lvgl/src/libs/thorvg/rapidjson/internal/diyfp.h \
    lvgl/src/libs/thorvg/rapidjson/internal/dtoa.h \
    lvgl/src/libs/thorvg/rapidjson/internal/ieee754.h \
    lvgl/src/libs/thorvg/rapidjson/internal/itoa.h \
    lvgl/src/libs/thorvg/rapidjson/internal/meta.h \
    lvgl/src/libs/thorvg/rapidjson/internal/pow10.h \
    lvgl/src/libs/thorvg/rapidjson/internal/regex.h \
    lvgl/src/libs/thorvg/rapidjson/internal/stack.h \
    lvgl/src/libs/thorvg/rapidjson/internal/strfunc.h \
    lvgl/src/libs/thorvg/rapidjson/internal/strtod.h \
    lvgl/src/libs/thorvg/rapidjson/internal/swap.h \
    lvgl/src/libs/thorvg/rapidjson/istreamwrapper.h \
    lvgl/src/libs/thorvg/rapidjson/memorybuffer.h \
    lvgl/src/libs/thorvg/rapidjson/memorystream.h \
    lvgl/src/libs/thorvg/rapidjson/msinttypes/inttypes.h \
    lvgl/src/libs/thorvg/rapidjson/msinttypes/stdint.h \
    lvgl/src/libs/thorvg/rapidjson/ostreamwrapper.h \
    lvgl/src/libs/thorvg/rapidjson/pointer.h \
    lvgl/src/libs/thorvg/rapidjson/prettywriter.h \
    lvgl/src/libs/thorvg/rapidjson/rapidjson.h \
    lvgl/src/libs/thorvg/rapidjson/reader.h \
    lvgl/src/libs/thorvg/rapidjson/schema.h \
    lvgl/src/libs/thorvg/rapidjson/stream.h \
    lvgl/src/libs/thorvg/rapidjson/stringbuffer.h \
    lvgl/src/libs/thorvg/rapidjson/uri.h \
    lvgl/src/libs/thorvg/rapidjson/writer.h \
    lvgl/src/libs/thorvg/thorvg.h \
    lvgl/src/libs/thorvg/thorvg_capi.h \
    lvgl/src/libs/thorvg/thorvg_lottie.h \
    lvgl/src/libs/thorvg/tvgAnimation.h \
    lvgl/src/libs/thorvg/tvgArray.h \
    lvgl/src/libs/thorvg/tvgBinaryDesc.h \
    lvgl/src/libs/thorvg/tvgCanvas.h \
    lvgl/src/libs/thorvg/tvgCommon.h \
    lvgl/src/libs/thorvg/tvgCompressor.h \
    lvgl/src/libs/thorvg/tvgFill.h \
    lvgl/src/libs/thorvg/tvgFrameModule.h \
    lvgl/src/libs/thorvg/tvgInlist.h \
    lvgl/src/libs/thorvg/tvgIteratorAccessor.h \
    lvgl/src/libs/thorvg/tvgLines.h \
    lvgl/src/libs/thorvg/tvgLoadModule.h \
    lvgl/src/libs/thorvg/tvgLoader.h \
    lvgl/src/libs/thorvg/tvgLock.h \
    lvgl/src/libs/thorvg/tvgLottieBuilder.h \
    lvgl/src/libs/thorvg/tvgLottieExpressions.h \
    lvgl/src/libs/thorvg/tvgLottieInterpolator.h \
    lvgl/src/libs/thorvg/tvgLottieLoader.h \
    lvgl/src/libs/thorvg/tvgLottieModel.h \
    lvgl/src/libs/thorvg/tvgLottieParser.h \
    lvgl/src/libs/thorvg/tvgLottieParserHandler.h \
    lvgl/src/libs/thorvg/tvgLottieProperty.h \
    lvgl/src/libs/thorvg/tvgMath.h \
    lvgl/src/libs/thorvg/tvgPaint.h \
    lvgl/src/libs/thorvg/tvgPicture.h \
    lvgl/src/libs/thorvg/tvgRawLoader.h \
    lvgl/src/libs/thorvg/tvgRender.h \
    lvgl/src/libs/thorvg/tvgSaveModule.h \
    lvgl/src/libs/thorvg/tvgScene.h \
    lvgl/src/libs/thorvg/tvgShape.h \
    lvgl/src/libs/thorvg/tvgStr.h \
    lvgl/src/libs/thorvg/tvgSvgCssStyle.h \
    lvgl/src/libs/thorvg/tvgSvgLoader.h \
    lvgl/src/libs/thorvg/tvgSvgLoaderCommon.h \
    lvgl/src/libs/thorvg/tvgSvgPath.h \
    lvgl/src/libs/thorvg/tvgSvgSceneBuilder.h \
    lvgl/src/libs/thorvg/tvgSvgUtil.h \
    lvgl/src/libs/thorvg/tvgSwCommon.h \
    lvgl/src/libs/thorvg/tvgSwRasterAvx.h \
    lvgl/src/libs/thorvg/tvgSwRasterC.h \
    lvgl/src/libs/thorvg/tvgSwRasterNeon.h \
    lvgl/src/libs/thorvg/tvgSwRasterTexmap.h \
    lvgl/src/libs/thorvg/tvgSwRenderer.h \
    lvgl/src/libs/thorvg/tvgTaskScheduler.h \
    lvgl/src/libs/thorvg/tvgText.h \
    lvgl/src/libs/thorvg/tvgXmlParser.h \
    lvgl/src/libs/tiny_ttf/lv_tiny_ttf.h \
    lvgl/src/libs/tiny_ttf/stb_rect_pack.h \
    lvgl/src/libs/tiny_ttf/stb_truetype_htcw.h \
    lvgl/src/libs/tjpgd/lv_tjpgd.h \
    lvgl/src/libs/tjpgd/tjpgd.h \
    lvgl/src/libs/tjpgd/tjpgdcnf.h \
    lvgl/src/lv_api_map_v8.h \
    lvgl/src/lv_api_map_v9_0.h \
    lvgl/src/lv_api_map_v9_1.h \
    lvgl/src/lv_conf_internal.h \
    lvgl/src/lv_conf_kconfig.h \
    lvgl/src/lv_init.h \
    lvgl/src/lvgl.h \
    lvgl/src/lvgl_private.h \
    lvgl/src/misc/cache/lv_cache.h \
    lvgl/src/misc/cache/lv_cache_entry.h \
    lvgl/src/misc/cache/lv_cache_entry_private.h \
    lvgl/src/misc/cache/lv_cache_lru_rb.h \
    lvgl/src/misc/cache/lv_cache_private.h \
    lvgl/src/misc/cache/lv_image_cache.h \
    lvgl/src/misc/cache/lv_image_header_cache.h \
    lvgl/src/misc/lv_anim.h \
    lvgl/src/misc/lv_anim_private.h \
    lvgl/src/misc/lv_anim_timeline.h \
    lvgl/src/misc/lv_area.h \
    lvgl/src/misc/lv_area_private.h \
    lvgl/src/misc/lv_array.h \
    lvgl/src/misc/lv_assert.h \
    lvgl/src/misc/lv_async.h \
    lvgl/src/misc/lv_bidi.h \
    lvgl/src/misc/lv_bidi_private.h \
    lvgl/src/misc/lv_color.h \
    lvgl/src/misc/lv_color_op.h \
    lvgl/src/misc/lv_color_op_private.h \
    lvgl/src/misc/lv_event.h \
    lvgl/src/misc/lv_event_private.h \
    lvgl/src/misc/lv_fs.h \
    lvgl/src/misc/lv_fs_private.h \
    lvgl/src/misc/lv_ll.h \
    lvgl/src/misc/lv_log.h \
    lvgl/src/misc/lv_lru.h \
    lvgl/src/misc/lv_math.h \
    lvgl/src/misc/lv_matrix.h \
    lvgl/src/misc/lv_palette.h \
    lvgl/src/misc/lv_profiler.h \
    lvgl/src/misc/lv_profiler_builtin.h \
    lvgl/src/misc/lv_profiler_builtin_private.h \
    lvgl/src/misc/lv_rb.h \
    lvgl/src/misc/lv_rb_private.h \
    lvgl/src/misc/lv_style.h \
    lvgl/src/misc/lv_style_gen.h \
    lvgl/src/misc/lv_style_private.h \
    lvgl/src/misc/lv_templ.h \
    lvgl/src/misc/lv_text.h \
    lvgl/src/misc/lv_text_ap.h \
    lvgl/src/misc/lv_text_private.h \
    lvgl/src/misc/lv_timer.h \
    lvgl/src/misc/lv_timer_private.h \
    lvgl/src/misc/lv_types.h \
    lvgl/src/misc/lv_utils.h \
    lvgl/src/osal/lv_cmsis_rtos2.h \
    lvgl/src/osal/lv_freertos.h \
    lvgl/src/osal/lv_mqx.h \
    lvgl/src/osal/lv_os.h \
    lvgl/src/osal/lv_os_none.h \
    lvgl/src/osal/lv_os_private.h \
    lvgl/src/osal/lv_pthread.h \
    lvgl/src/osal/lv_rtthread.h \
    lvgl/src/osal/lv_windows.h \
    lvgl/src/others/file_explorer/lv_file_explorer.h \
    lvgl/src/others/file_explorer/lv_file_explorer_private.h \
    lvgl/src/others/fragment/lv_fragment.h \
    lvgl/src/others/fragment/lv_fragment_private.h \
    lvgl/src/others/gridnav/lv_gridnav.h \
    lvgl/src/others/ime/lv_ime_pinyin.h \
    lvgl/src/others/ime/lv_ime_pinyin_private.h \
    lvgl/src/others/imgfont/lv_imgfont.h \
    lvgl/src/others/monkey/lv_monkey.h \
    lvgl/src/others/monkey/lv_monkey_private.h \
    lvgl/src/others/observer/lv_observer.h \
    lvgl/src/others/observer/lv_observer_private.h \
    lvgl/src/others/snapshot/lv_snapshot.h \
    lvgl/src/others/sysmon/lv_sysmon.h \
    lvgl/src/others/sysmon/lv_sysmon_private.h \
    lvgl/src/others/vg_lite_tvg/vg_lite.h \
    lvgl/src/stdlib/builtin/lv_tlsf.h \
    lvgl/src/stdlib/builtin/lv_tlsf_private.h \
    lvgl/src/stdlib/lv_mem.h \
    lvgl/src/stdlib/lv_mem_private.h \
    lvgl/src/stdlib/lv_sprintf.h \
    lvgl/src/stdlib/lv_string.h \
    lvgl/src/themes/default/lv_theme_default.h \
    lvgl/src/themes/lv_theme.h \
    lvgl/src/themes/lv_theme_private.h \
    lvgl/src/themes/mono/lv_theme_mono.h \
    lvgl/src/themes/simple/lv_theme_simple.h \
    lvgl/src/tick/lv_tick.h \
    lvgl/src/tick/lv_tick_private.h \
    lvgl/src/widgets/animimage/lv_animimage.h \
    lvgl/src/widgets/animimage/lv_animimage_private.h \
    lvgl/src/widgets/arc/lv_arc.h \
    lvgl/src/widgets/arc/lv_arc_private.h \
    lvgl/src/widgets/bar/lv_bar.h \
    lvgl/src/widgets/bar/lv_bar_private.h \
    lvgl/src/widgets/button/lv_button.h \
    lvgl/src/widgets/button/lv_button_private.h \
    lvgl/src/widgets/buttonmatrix/lv_buttonmatrix.h \
    lvgl/src/widgets/buttonmatrix/lv_buttonmatrix_private.h \
    lvgl/src/widgets/calendar/lv_calendar.h \
    lvgl/src/widgets/calendar/lv_calendar_chinese.h \
    lvgl/src/widgets/calendar/lv_calendar_chinese_private.h \
    lvgl/src/widgets/calendar/lv_calendar_header_arrow.h \
    lvgl/src/widgets/calendar/lv_calendar_header_dropdown.h \
    lvgl/src/widgets/calendar/lv_calendar_private.h \
    lvgl/src/widgets/canvas/lv_canvas.h \
    lvgl/src/widgets/canvas/lv_canvas_private.h \
    lvgl/src/widgets/chart/lv_chart.h \
    lvgl/src/widgets/chart/lv_chart_private.h \
    lvgl/src/widgets/checkbox/lv_checkbox.h \
    lvgl/src/widgets/checkbox/lv_checkbox_private.h \
    lvgl/src/widgets/dropdown/lv_dropdown.h \
    lvgl/src/widgets/dropdown/lv_dropdown_private.h \
    lvgl/src/widgets/image/lv_image.h \
    lvgl/src/widgets/image/lv_image_private.h \
    lvgl/src/widgets/imagebutton/lv_imagebutton.h \
    lvgl/src/widgets/imagebutton/lv_imagebutton_private.h \
    lvgl/src/widgets/keyboard/lv_keyboard.h \
    lvgl/src/widgets/keyboard/lv_keyboard_private.h \
    lvgl/src/widgets/label/lv_label.h \
    lvgl/src/widgets/label/lv_label_private.h \
    lvgl/src/widgets/led/lv_led.h \
    lvgl/src/widgets/led/lv_led_private.h \
    lvgl/src/widgets/line/lv_line.h \
    lvgl/src/widgets/line/lv_line_private.h \
    lvgl/src/widgets/list/lv_list.h \
    lvgl/src/widgets/lottie/lv_lottie.h \
    lvgl/src/widgets/lottie/lv_lottie_private.h \
    lvgl/src/widgets/menu/lv_menu.h \
    lvgl/src/widgets/menu/lv_menu_private.h \
    lvgl/src/widgets/msgbox/lv_msgbox.h \
    lvgl/src/widgets/msgbox/lv_msgbox_private.h \
    lvgl/src/widgets/objx_templ/lv_objx_templ.h \
    lvgl/src/widgets/property/lv_obj_property_names.h \
    lvgl/src/widgets/property/lv_style_properties.h \
    lvgl/src/widgets/roller/lv_roller.h \
    lvgl/src/widgets/roller/lv_roller_private.h \
    lvgl/src/widgets/scale/lv_scale.h \
    lvgl/src/widgets/scale/lv_scale_private.h \
    lvgl/src/widgets/slider/lv_slider.h \
    lvgl/src/widgets/slider/lv_slider_private.h \
    lvgl/src/widgets/span/lv_span.h \
    lvgl/src/widgets/span/lv_span_private.h \
    lvgl/src/widgets/spinbox/lv_spinbox.h \
    lvgl/src/widgets/spinbox/lv_spinbox_private.h \
    lvgl/src/widgets/spinner/lv_spinner.h \
    lvgl/src/widgets/switch/lv_switch.h \
    lvgl/src/widgets/switch/lv_switch_private.h \
    lvgl/src/widgets/table/lv_table.h \
    lvgl/src/widgets/table/lv_table_private.h \
    lvgl/src/widgets/tabview/lv_tabview.h \
    lvgl/src/widgets/tabview/lv_tabview_private.h \
    lvgl/src/widgets/textarea/lv_textarea.h \
    lvgl/src/widgets/textarea/lv_textarea_private.h \
    lvgl/src/widgets/tileview/lv_tileview.h \
    lvgl/src/widgets/tileview/lv_tileview_private.h \
    lvgl/src/widgets/win/lv_win.h \
    lvgl/src/widgets/win/lv_win_private.h \

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target
